### ISSUE TITLE
API Call: Delete Project not working anymore

### ISSUE THREAD

**Issue by kiwo** [opendevstack/ods-provisioning-app#294]
**Describe the bug**
* "Cleanup" method is being used by ProvApp REST Api to delete Projects. 
* Because Jenkins calls are ASYC JenkinsPipelineAdapter cant do cleanup as before 
( Cleanup job can be executed before actual project creation happens) -> Cleanup procedure was disabled in JenkinsPipelineAdapter 

**To Reproduce**
call REST API to delete Project

**Expected behavior**
Openshift Projects are being deletet 

***Todo:***
- [x]  create Jenkinsjob in ods-core
- [ ]  build "delete" Function in JenkinsPipelineAdapter (create a new function desigend to delete projects and dont rely on "cleanup")
- [ ] fix org.opendevstack.provision.controller.E2EProjectAPIControllerTest#testQuickstarterProvisionOnNewOpenProjectInclDelete

**Comment by stefanlack** [comment]
Note that org.opendevstack.provision.controller.E2EProjectAPIControllerTest#testQuickstarterProvisionOnNewOpenProjectInclDelete has also to be fixed.

**Comment by michaelsauter** [comment]
@kiwo Rundeck was also async?! Should not have changed ... this is a MUST for ODS 2.

**Comment by kiwo** [comment]
in rundeck jobs where running in serial.

**Comment by michaelsauter** [comment]
Hmm ... nothing waited for the completion of a Rundeck job though. At least there was no feedback in the prov app when it completed? Sometimes the job would fail and you would not know until you looked in Rundeck.

**Comment by stefanlack** [comment]
will be fixed via #295
