### ISSUE TITLE
API Call: Delete Component not working anymore

### ISSUE THREAD

**Issue by stefanlack** [opendevstack/ods-provisioning-app#296]
**Describe the bug**
* "Cleanup" method is being used by ProvApp REST Api to delete Projects. 
* Because Jenkins calls are ASYC JenkinsPipelineAdapter cant do cleanup as before 
( Cleanup job can be executed before actual project creation happens) -> Cleanup procedure was disabled in JenkinsPipelineAdapter 

**To Reproduce**
call REST API to delete Project

**Expected behavior**
Openshift compontens based on quickstarters are being deleted

***TODO:***
- [x]  create Jenkinsjob in ods-core to delete components from openshift (-> @kiwo )
- [x]  build "delete-component" Function in JenkinsPipelineAdapter (create a new function desigend to delete components. (-> @stefanlack )
- [x] Activate and fix test E2EProjectAPIControllerTest.testQuickstarterProvisionOnNewOpenProjectInclDeleteSingleComponent  (based on #295)/ function that is called to delete a single component is missing (-> @stefanlack )

***Additional Context***

Code where _delete compontent function_ was removed: https://github.com/opendevstack/ods-provisioning-app/commit/86e56adb5d85ac07c01fd312e05fdc06577e0d13#r36243487

**Comment by stefanlack** [comment]
@michaelsauter @clemensutschig : do you know if component deletion was implemented via rundeck? We (@kiwo  and I) couldn't find a shell scirpt inside old ods-project-quickstarters repro.

**Comment by michaelsauter** [comment]
@stefanlack @kiwo Hmm, I found it here: https://github.com/opendevstack/ods-project-quickstarters/tree/1.1.x/rundeck-jobs/openshift.

It is not there anymore in 1.2.x ....

**Comment by michaelsauter** [comment]
Script is at https://github.com/opendevstack/ods-project-quickstarters/blob/1.1.x/ocp-templates/scripts/delete-component.sh. That did also not make it into 1.2.x ...

**Comment by clemensutschig** [comment]
@michaelsauter  - yup indeed .. it was there in 1.0.x ... just checked :) 

utschig@WKS0000627058 MINGW64 /c/code_bix/opendevstack_at_BIX/ods-project-quickstarters/rundeck-jobs/openshift (ods_1.0.x)
$ ls
   delete-component.yaml

and secondly ... 

utschig@WKS0000627058 MINGW64 /c/code_bix/opendevstack_at_BIX/ods-project-quickstarters/ocp-templates/scripts (ods_1.0.x)
$ ls
delete-component.sh*

**Comment by michaelsauter** [comment]
You either want to delete all resources with the label `app=PROJECT-COMPONENT` or you process the templates and delete the resources in it ...

**Comment by stefanlack** [comment]
Done:
- uild "delete-component" Function in JenkinsPipelineAdapter (create a new function desigend to delete components. (-> @stefanlack )
- Activate and fix test E2EProjectAPIControllerTest.testQuickstarterProvisionOnNewOpenProjectInclDeleteSingleComponent (based on #295)/ function that is called to delete a single component is missing (-> @stefanlack )
